---
- name: Add the can module
  community.general.modprobe:
    name: can
    state: present

- name: Add the can_raw module
  community.general.modprobe:
    name: can_raw
    state: present

- name: Add the mcp251x module
  community.general.modprobe:
    name: mcp251x
    state: present
